### ISSUE TITLE
decimal-arithmetic dismally fails a simple test while casting

### ISSUE THREAD

**Issue by tebello-thejane** [verement/decimal-arithmetic#1]
What am I doing wrong here?

```haskell
module Main where

import Numeric.Decimal

type Yada = Decimal P9 RoundHalfEven
type Dollar = Decimal P2 RoundHalfEven

main :: IO ()
main = do
  let btc = 0.05463 :: Yada
  let prc = 36523 :: Dollar
  let fee = 0.01

  print $ cast btc * prc * (1 - fee)
```

This prints `2.0E+3`. Replacing the last line with ` print $ cast btc * prc * (1 - fee)` prints `2001.0969`.

The ideal, exact value is `1975.2989751`.

Am I abusing this library in some way? I am guessing that the library is prematurely truncating accuracy way before it is called to print out the answer -- in fact, this is worse than just using double: the naïve `print $ 0.05463 * 36523 * (1 - 0.01)` gives `1975.2989750999998`.

**Comment by verement** [comment]
The type `Decimal P2 RoundHalfEven` means numbers have a maximum of two significant digits. (It does not mean just the number of places after the decimal point; it means the total number of digits in the entire value, excluding the exponent.) So `prc = 36523 :: Dollar` immediately becomes `3.7E+4` even before your calculation, losing significant precision.

Since `prc` has 5 digits, you would need to use at least this much precision in the type, e.g. `Decimal P5 RoundHalfEven` (or equivalently, `ExtendedDecimal P5`) in order to retain full precision.

Since the ideal, exact value of your calculation has 11 significant digits, you would need to use at least this much precision to obtain it:

```haskell
module Main where

import Numeric.Decimal

type Yada = Decimal P9 RoundHalfEven
type Dollar = Decimal P5 RoundHalfEven

main :: IO ()
main = do
  let btc = 0.05463 :: Yada
  let prc = 36523 :: Dollar
  let fee = 0.01

  print (cast btc * cast prc * (1 - fee) :: ExtendedDecimal P11)
```

This prints `1975.2989751`.
